### ISSUE TITLE
Deprecation warning with recent pytest

### ISSUE THREAD

**Issue by rgilton** [carsongee/pytest-pylint#168] opened 2022-07-08 10:10 UTC
With pytest 7.1.2, I get the following warning:

```
../../../../../../.local/share/virtualenvs/server-IJExtVut/lib/python3.10/site-packages/pytest_pylint/plugin.py:295: 129 warnings
  /home/rob/.local/share/virtualenvs/server-IJExtVut/lib/python3.10/site-packages/pytest_pylint/plugin.py:295: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to PylintFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    _self = getattr(super(), 'from_parent', cls)(parent, fspath=fspath)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

Current workaround: `pytest -W ignore:::pytest_pylint.plugin:295`

**Comment by carsongee** [comment] 2022-09-10 22:06
Duplicate of #166

**Closed by carsongee** 2022-09-10 22:06 UTC
